### ISSUE TITLE
Feature Request: set global to latest

### ISSUE THREAD

**Issue by ZaxR** [momo-lab/pyenv-install-latest#2]
First off, thank you for this plugin - it's hugely useful.

I would like to request that the latest syntax be integrated elsewhere in pyenv, particularly as an option when setting local/global versions. For example, something like:

pyenv install-latest
pyenv global latest

Thanks in advance for the consideration!

**Comment by momo-lab** [comment]
Nice idea!
I made [xxenv-latest](https://github.com/momo-lab/xxenv-latest) and I want you to try it.

**Comment by momo-lab** [comment]
If you use xxenv-latest, you can write like below.

```shell
$ pyenv latest install
$ pyenv latest global
```
