### ISSUE TITLE
Feature Request: add option to delete old versions

### ISSUE THREAD

**Issue by NathanUrwin** [momo-lab/pyenv-install-latest#5]

**Comment by momo-lab** [comment]
I made [xxenv-latest](https://github.com/momo-lab/xxenv-latest) and I want you to try it.

Example using xxenv-latest:
```shell
$ pyenv versions
  2.7.13
  2.7.14
  2.7.15
  3.7.1
* 3.7.2 (set by /home/username/.pyenv/version)
$ pyenv latest uninstall 2.7
pyenv: remove /home/username/.pyenv/versions/2.7.13? y
pyenv: remove /home/username/.pyenv/versions/2.7.14? y
$ pyenv versions
  2.7.15
  3.7.1
* 3.7.2 (set by /home/username/.pyenv/versions/2.7.15)
```

**Comment by NathanUrwin** [comment]
Hey @momo-lab 👋 

Thanks for the reply! Is that project meant to replace all your **env-install-latest plugins? Looks perfect! 😄

**Comment by momo-lab** [comment]
Yes. I will replace it.
Has your request been resolved? I want to close this issue.
